name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: yarn
    - run: |
        corepack enable
        yarn install --frozen-lockfile

    - run: yarn run lint --no-fix --max-warnings 0
    - run: yarn run test:unit